[project]
name = ""
version = "0.0.1"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]",
    "duckdb",
]

[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "pytest-cov>=4.1.0",
]

[tool.uv]
package = false
